export type PresetStyle = "vivid" | "matte" | "clean";

export type PresetColorCategory =
  | "blue"
  | "cyan"
  | "green"
  | "yellow"
  | "orange"
  | "red"
  | "pink"
  | "purple"
  | "indigo"
  | "lime"
  | "brown"
  | "mono";

export interface AppearancePreset {
  id: string;
  label: string;
  description: string;
  category: PresetColorCategory;
  categoryLabel: string;
  style: PresetStyle;
  styleLabel: string;
  swatchColor: string;
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  mainColor: string;
  sidebarColor: string;
  rightPanelColor: string;
  cardColor: string;
  panelColor: string;
  inputColor: string;
  borderColor: string;
  textColor: string;
  mutedTextColor: string;
  navActiveColor: string;
  buttonTextColor: string;
  backgroundOpacity: number;
  mainOpacity: number;
  surfaceOpacity: number;
  panelOpacity: number;
  inputOpacity: number;
  sidebarOpacity: number;
  rightPanelOpacity: number;
  navActiveOpacity: number;
  borderOpacity: number;
  backgroundImageOpacity: number;
  sidebarImageOpacity: number;
}

export const presetCategoryList: Array<{ id: PresetColorCategory | "all"; label: string; color: string }> = [
  { id: "all", label: "Todas as Cores", color: "#60A5FA" },
  { id: "blue", label: "Azul", color: "#3B82F6" },
  { id: "cyan", label: "Ciano / Aqua", color: "#06B6D4" },
  { id: "green", label: "Verde / Esmeralda", color: "#10B981" },
  { id: "yellow", label: "Amarelo / Dourado", color: "#F59E0B" },
  { id: "orange", label: "Laranja / Fogo", color: "#EA580C" },
  { id: "red", label: "Vermelho / Rubi", color: "#DC2626" },
  { id: "pink", label: "Rosa / Magenta", color: "#DB2777" },
  { id: "purple", label: "Roxo / Violeta", color: "#9333EA" },
  { id: "indigo", label: "Índigo / Safira", color: "#4F46E5" },
  { id: "lime", label: "Lima / Neon", color: "#84CC16" },
  { id: "brown", label: "Café / Âmbar", color: "#D97706" },
  { id: "mono", label: "Monocromático", color: "#E2E8F0" },
];

export const presetStyleList: Array<{
  id: PresetStyle | "all";
  label: string;
  tag: string;
  description: string;
  iconTone: string;
}> = [
  {
    id: "all",
    label: "Todos os Estilos",
    tag: "TODOS",
    description: "Visualizar todas as combinações de estilo e tonalidade.",
    iconTone: "blue",
  },
  {
    id: "vivid",
    label: "Vívido",
    tag: "VÍVIDO ⚡",
    description: "Cores intensas, saturação alta, brilho marcante e contraste energético.",
    iconTone: "amber",
  },
  {
    id: "matte",
    label: "Matte",
    tag: "MATTE 🛋️",
    description: "Tons aveludados, suaves, anti-fadiga e ultra confortáveis para os olhos.",
    iconTone: "emerald",
  },
  {
    id: "clean",
    label: "Clean",
    tag: "CLEAN ✨",
    description: "Design cristalino, translúcido, moderno, minimalista e arejado.",
    iconTone: "sky",
  },
];

export const defaultAppearancePreset: AppearancePreset = {
  id: "night-dark",
  label: "Night Dark",
  description: "Escuro clássico com azul e excelente contraste geral.",
  category: "blue",
  categoryLabel: "Azul",
  style: "matte",
  styleLabel: "Matte",
  swatchColor: "#3B82F6",
  primaryColor: "#3B82F6",
  secondaryColor: "#60A5FA",
  backgroundColor: "#0D1117",
  mainColor: "#0D1117",
  sidebarColor: "#0A0E14",
  rightPanelColor: "#0B0F15",
  cardColor: "#161B22",
  panelColor: "#0D1117",
  inputColor: "#0B0F15",
  borderColor: "#FFFFFF",
  textColor: "#FFFFFF",
  mutedTextColor: "#94A3B8",
  navActiveColor: "#3B82F6",
  buttonTextColor: "#FFFFFF",
  backgroundOpacity: 1,
  mainOpacity: 0.38,
  surfaceOpacity: 0.82,
  panelOpacity: 0.7,
  inputOpacity: 0.92,
  sidebarOpacity: 0.96,
  rightPanelOpacity: 0.88,
  navActiveOpacity: 0.16,
  borderOpacity: 0.1,
  backgroundImageOpacity: 0.28,
  sidebarImageOpacity: 0.22,
};

export const appearancePresets: AppearancePreset[] = [
  // --- CLÁSSICOS ORIGINAIS (Compatibilidade) ---
  defaultAppearancePreset,
  {
    id: "blue-sky",
    label: "Blue Sky",
    description: "Azul celeste e visual limpo com tons oceânicos.",
    category: "blue",
    categoryLabel: "Azul",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#0EA5E9",
    primaryColor: "#0EA5E9",
    secondaryColor: "#38BDF8",
    backgroundColor: "#07111F",
    mainColor: "#0B1726",
    sidebarColor: "#07111F",
    rightPanelColor: "#081827",
    cardColor: "#0F2335",
    panelColor: "#0A1826",
    inputColor: "#07111F",
    borderColor: "#7DD3FC",
    textColor: "#F8FAFC",
    mutedTextColor: "#B6CEE3",
    navActiveColor: "#0EA5E9",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.92,
    mainOpacity: 0.44,
    surfaceOpacity: 0.78,
    panelOpacity: 0.72,
    inputOpacity: 0.9,
    sidebarOpacity: 0.88,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.2,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.3,
  },
  {
    id: "yellow-sun",
    label: "Yellow Sun",
    description: "Amarelo quente e destaque solar revigorante.",
    category: "yellow",
    categoryLabel: "Amarelo",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#F59E0B",
    primaryColor: "#F59E0B",
    secondaryColor: "#FACC15",
    backgroundColor: "#17120A",
    mainColor: "#18130B",
    sidebarColor: "#100D08",
    rightPanelColor: "#161006",
    cardColor: "#21190B",
    panelColor: "#15100A",
    inputColor: "#100D08",
    borderColor: "#FDE68A",
    textColor: "#FFF7ED",
    mutedTextColor: "#D8C9AE",
    navActiveColor: "#F59E0B",
    buttonTextColor: "#120A02",
    backgroundOpacity: 0.9,
    mainOpacity: 0.44,
    surfaceOpacity: 0.76,
    panelOpacity: 0.72,
    inputOpacity: 0.9,
    sidebarOpacity: 0.9,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.22,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.26,
  },
  {
    id: "light-mode",
    label: "Light Mode",
    description: "Cores claras, fundo branco e alto contraste diurno.",
    category: "mono",
    categoryLabel: "Monocromático",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#FFFFFF",
    primaryColor: "#2563EB",
    secondaryColor: "#0284C7",
    backgroundColor: "#F1F5F9",
    mainColor: "#F8FAFC",
    sidebarColor: "#FFFFFF",
    rightPanelColor: "#FFFFFF",
    cardColor: "#FFFFFF",
    panelColor: "#F8FAFC",
    inputColor: "#FFFFFF",
    borderColor: "#CBD5E1",
    textColor: "#0F172A",
    mutedTextColor: "#475569",
    navActiveColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 1,
    mainOpacity: 1,
    surfaceOpacity: 1,
    panelOpacity: 1,
    inputOpacity: 1,
    sidebarOpacity: 1,
    rightPanelOpacity: 1,
    navActiveOpacity: 0.15,
    borderOpacity: 0.9,
    backgroundImageOpacity: 0.12,
    sidebarImageOpacity: 0.14,
  },
  {
    id: "emerald-cave",
    label: "Emerald Cave",
    description: "Verde esmeralda frio com atmosfera profunda de caverna.",
    category: "green",
    categoryLabel: "Verde",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#10B981",
    primaryColor: "#10B981",
    secondaryColor: "#34D399",
    backgroundColor: "#07130F",
    mainColor: "#081914",
    sidebarColor: "#06100D",
    rightPanelColor: "#071611",
    cardColor: "#10231D",
    panelColor: "#0A1713",
    inputColor: "#06100D",
    borderColor: "#6EE7B7",
    textColor: "#ECFDF5",
    mutedTextColor: "#A8CDBF",
    navActiveColor: "#10B981",
    buttonTextColor: "#06100D",
    backgroundOpacity: 0.94,
    mainOpacity: 0.42,
    surfaceOpacity: 0.78,
    panelOpacity: 0.72,
    inputOpacity: 0.9,
    sidebarOpacity: 0.92,
    rightPanelOpacity: 0.86,
    navActiveOpacity: 0.2,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "red-velt",
    label: "Red Velt",
    description: "Vermelho profundo aveludado com contraste premium.",
    category: "red",
    categoryLabel: "Vermelho",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#DC2626",
    primaryColor: "#DC2626",
    secondaryColor: "#FB7185",
    backgroundColor: "#150708",
    mainColor: "#17090A",
    sidebarColor: "#100506",
    rightPanelColor: "#17090A",
    cardColor: "#241011",
    panelColor: "#18090A",
    inputColor: "#120607",
    borderColor: "#FCA5A5",
    textColor: "#FFF1F2",
    mutedTextColor: "#E9B8BD",
    navActiveColor: "#DC2626",
    buttonTextColor: "#FFF7F7",
    backgroundOpacity: 0.94,
    mainOpacity: 0.44,
    surfaceOpacity: 0.8,
    panelOpacity: 0.72,
    inputOpacity: 0.92,
    sidebarOpacity: 0.94,
    rightPanelOpacity: 0.88,
    navActiveOpacity: 0.22,
    borderOpacity: 0.18,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 1. AZUL (BLUE) =================
  {
    id: "blue-vivid",
    label: "Azul Cyber Vívido",
    description: "Azul elétrico de alta energia com contraste vibrante e iluminação marcante.",
    category: "blue",
    categoryLabel: "Azul",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#2563EB",
    primaryColor: "#2563EB",
    secondaryColor: "#38BDF8",
    backgroundColor: "#080F1D",
    mainColor: "#0D1A2D",
    sidebarColor: "#060C17",
    rightPanelColor: "#080F1D",
    cardColor: "#11223B",
    panelColor: "#0D1A2D",
    inputColor: "#080F1D",
    borderColor: "#60A5FA",
    textColor: "#F8FAFC",
    mutedTextColor: "#94A3B8",
    navActiveColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.96,
    mainOpacity: 0.44,
    surfaceOpacity: 0.85,
    panelOpacity: 0.75,
    inputOpacity: 0.92,
    sidebarOpacity: 0.94,
    rightPanelOpacity: 0.88,
    navActiveOpacity: 0.22,
    borderOpacity: 0.22,
    backgroundImageOpacity: 0.26,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "blue-matte",
    label: "Azul Ardósia Matte",
    description: "Tons aveludados e suaves, sem reflexos fortes, ideais para descanso visual em longas sessões.",
    category: "blue",
    categoryLabel: "Azul",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#475569",
    primaryColor: "#475569",
    secondaryColor: "#64748B",
    backgroundColor: "#0F141C",
    mainColor: "#141A24",
    sidebarColor: "#0C1017",
    rightPanelColor: "#0F141C",
    cardColor: "#1B222E",
    panelColor: "#141A24",
    inputColor: "#0F141C",
    borderColor: "#334155",
    textColor: "#E2E8F0",
    mutedTextColor: "#94A3B8",
    navActiveColor: "#475569",
    buttonTextColor: "#F8FAFC",
    backgroundOpacity: 0.92,
    mainOpacity: 0.35,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.92,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.12,
    backgroundImageOpacity: 0.18,
    sidebarImageOpacity: 0.18,
  },
  {
    id: "blue-clean",
    label: "Azul Glacial Clean",
    description: "Visual límpido e cristalino, efeito vidro arejado e estética minimalista.",
    category: "blue",
    categoryLabel: "Azul",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#0284C7",
    primaryColor: "#0284C7",
    secondaryColor: "#7DD3FC",
    backgroundColor: "#07111E",
    mainColor: "#0B192A",
    sidebarColor: "#060E1A",
    rightPanelColor: "#081321",
    cardColor: "#0E2137",
    panelColor: "#0A1828",
    inputColor: "#07111E",
    borderColor: "#38BDF8",
    textColor: "#F0F9FF",
    mutedTextColor: "#BAE6FD",
    navActiveColor: "#0284C7",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.65,
    panelOpacity: 0.55,
    inputOpacity: 0.85,
    sidebarOpacity: 0.86,
    rightPanelOpacity: 0.8,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 2. CIANO / TURQUESA (CYAN) =================
  {
    id: "cyan-vivid",
    label: "Ciano Neon Vívido",
    description: "Ciano elétrico ultra saturado com destaque tecnológico e iluminação cibernética.",
    category: "cyan",
    categoryLabel: "Ciano / Aqua",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#06B6D4",
    primaryColor: "#06B6D4",
    secondaryColor: "#22D3EE",
    backgroundColor: "#041419",
    mainColor: "#072027",
    sidebarColor: "#031014",
    rightPanelColor: "#05171C",
    cardColor: "#0B2B34",
    panelColor: "#072027",
    inputColor: "#041419",
    borderColor: "#67E8F9",
    textColor: "#ECFEFF",
    mutedTextColor: "#A5F3FC",
    navActiveColor: "#06B6D4",
    buttonTextColor: "#041419",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "cyan-matte",
    label: "Menta Oceânica Matte",
    description: "Tons suaves de verde-água e ciano pastel, textura aveludada e descansada.",
    category: "cyan",
    categoryLabel: "Ciano / Aqua",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#14B8A6",
    primaryColor: "#0D9488",
    secondaryColor: "#5EEAD4",
    backgroundColor: "#081617",
    mainColor: "#0E1F20",
    sidebarColor: "#071213",
    rightPanelColor: "#091819",
    cardColor: "#14292B",
    panelColor: "#0E1F20",
    inputColor: "#081617",
    borderColor: "#115E59",
    textColor: "#F0FDFA",
    mutedTextColor: "#99F6E4",
    navActiveColor: "#0D9488",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.77,
    panelOpacity: 0.69,
    inputOpacity: 0.89,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.85,
    navActiveOpacity: 0.17,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "cyan-clean",
    label: "Aqua Diamante Clean",
    description: "Transparência pura com acentos ciano cristalino e bordas finas refinadas.",
    category: "cyan",
    categoryLabel: "Ciano / Aqua",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#22D3EE",
    primaryColor: "#0891B2",
    secondaryColor: "#A5F3FC",
    backgroundColor: "#051318",
    mainColor: "#081B22",
    sidebarColor: "#041014",
    rightPanelColor: "#06161B",
    cardColor: "#0C242C",
    panelColor: "#081B22",
    inputColor: "#051318",
    borderColor: "#22D3EE",
    textColor: "#F0FDFA",
    mutedTextColor: "#BAE6FD",
    navActiveColor: "#0891B2",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 3. VERDE / ESMERALDA (GREEN) =================
  {
    id: "green-vivid",
    label: "Esmeralda Neon Vívido",
    description: "Verde radioativo com alta luminescência e contraste extremo.",
    category: "green",
    categoryLabel: "Verde / Esmeralda",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#10B981",
    primaryColor: "#10B981",
    secondaryColor: "#34D399",
    backgroundColor: "#04140D",
    mainColor: "#082015",
    sidebarColor: "#03100A",
    rightPanelColor: "#051810",
    cardColor: "#0D2B1D",
    panelColor: "#082015",
    inputColor: "#04140D",
    borderColor: "#6EE7B7",
    textColor: "#ECFDF5",
    mutedTextColor: "#A7F3D0",
    navActiveColor: "#10B981",
    buttonTextColor: "#04140D",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "green-matte",
    label: "Verde Floresta Matte",
    description: "Verde musgo e sálvia suave com acabamento sem brilho para total conforto visual.",
    category: "green",
    categoryLabel: "Verde / Esmeralda",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#15803D",
    primaryColor: "#166534",
    secondaryColor: "#4ADE80",
    backgroundColor: "#0A140E",
    mainColor: "#0F1C14",
    sidebarColor: "#08100B",
    rightPanelColor: "#0B160F",
    cardColor: "#16261C",
    panelColor: "#0F1C14",
    inputColor: "#0A140E",
    borderColor: "#14532D",
    textColor: "#F0FDF4",
    mutedTextColor: "#86EFAC",
    navActiveColor: "#166534",
    buttonTextColor: "#F0FDF4",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "green-clean",
    label: "Menta Bio Clean",
    description: "Design minimalista com leveza orgânica e acentos menta arejados.",
    category: "green",
    categoryLabel: "Verde / Esmeralda",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#059669",
    primaryColor: "#059669",
    secondaryColor: "#6EE7B7",
    backgroundColor: "#05130D",
    mainColor: "#081B13",
    sidebarColor: "#040F0A",
    rightPanelColor: "#06150F",
    cardColor: "#0C2319",
    panelColor: "#081B13",
    inputColor: "#05130D",
    borderColor: "#34D399",
    textColor: "#ECFDF5",
    mutedTextColor: "#A7F3D0",
    navActiveColor: "#059669",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 4. AMARELO / DOURADO (YELLOW) =================
  {
    id: "yellow-vivid",
    label: "Amarelo Solar Vívido",
    description: "Explosão solar amarela e dourada com energia revigorante e alto brilho.",
    category: "yellow",
    categoryLabel: "Amarelo / Dourado",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#F59E0B",
    primaryColor: "#F59E0B",
    secondaryColor: "#FDE047",
    backgroundColor: "#141004",
    mainColor: "#1F1907",
    sidebarColor: "#100C03",
    rightPanelColor: "#171205",
    cardColor: "#2C230B",
    panelColor: "#1F1907",
    inputColor: "#141004",
    borderColor: "#FCD34D",
    textColor: "#FEFCE8",
    mutedTextColor: "#FDE68A",
    navActiveColor: "#F59E0B",
    buttonTextColor: "#141004",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "yellow-matte",
    label: "Mostarda Dourada Matte",
    description: "Tons quentes de mostarda e areia do deserto, aveludado e relaxante para a vista.",
    category: "yellow",
    categoryLabel: "Amarelo / Dourado",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#B45309",
    primaryColor: "#92400E",
    secondaryColor: "#F59E0B",
    backgroundColor: "#14110A",
    mainColor: "#1A160E",
    sidebarColor: "#0F0D07",
    rightPanelColor: "#14110A",
    cardColor: "#241F14",
    panelColor: "#1A160E",
    inputColor: "#14110A",
    borderColor: "#78350F",
    textColor: "#FEF3C7",
    mutedTextColor: "#D97706",
    navActiveColor: "#92400E",
    buttonTextColor: "#FEF3C7",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "yellow-clean",
    label: "Luz Dourada Clean",
    description: "Acentos âmbar sofisticados com fundo translúcido e elegante estética de vidro.",
    category: "yellow",
    categoryLabel: "Amarelo / Dourado",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#EAB308",
    primaryColor: "#CA8A04",
    secondaryColor: "#FEF08A",
    backgroundColor: "#110E05",
    mainColor: "#171307",
    sidebarColor: "#0C0A04",
    rightPanelColor: "#120F06",
    cardColor: "#201A0B",
    panelColor: "#171307",
    inputColor: "#110E05",
    borderColor: "#FACC15",
    textColor: "#FEFCE8",
    mutedTextColor: "#FDE047",
    navActiveColor: "#CA8A04",
    buttonTextColor: "#000000",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 5. LARANJA (ORANGE) =================
  {
    id: "orange-vivid",
    label: "Laranja Fogo Vívido",
    description: "Laranja incandescente com contraste dramático e personalidade forte.",
    category: "orange",
    categoryLabel: "Laranja / Fogo",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#EA580C",
    primaryColor: "#EA580C",
    secondaryColor: "#FB923C",
    backgroundColor: "#160A04",
    mainColor: "#221007",
    sidebarColor: "#100703",
    rightPanelColor: "#180B05",
    cardColor: "#2D170B",
    panelColor: "#221007",
    inputColor: "#160A04",
    borderColor: "#FDBA74",
    textColor: "#FFF7ED",
    mutedTextColor: "#FDBA74",
    navActiveColor: "#EA580C",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "orange-matte",
    label: "Terracota Quente Matte",
    description: "Tom de argila e cerâmica suave, proporcionando aconchego suave aos olhos.",
    category: "orange",
    categoryLabel: "Laranja / Fogo",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#C2410C",
    primaryColor: "#9A3412",
    secondaryColor: "#FB923C",
    backgroundColor: "#150D08",
    mainColor: "#1C120C",
    sidebarColor: "#0F0906",
    rightPanelColor: "#150D08",
    cardColor: "#251911",
    panelColor: "#1C120C",
    inputColor: "#150D08",
    borderColor: "#7C2D12",
    textColor: "#FFEDD5",
    mutedTextColor: "#FB923C",
    navActiveColor: "#9A3412",
    buttonTextColor: "#FFEDD5",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "orange-clean",
    label: "Pêssego Sunset Clean",
    description: "Leveza com toques de pêssego dourado em layout translúcido e moderno.",
    category: "orange",
    categoryLabel: "Laranja / Fogo",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#F97316",
    primaryColor: "#EA580C",
    secondaryColor: "#FFEDD5",
    backgroundColor: "#120A05",
    mainColor: "#180E08",
    sidebarColor: "#0D0704",
    rightPanelColor: "#130B06",
    cardColor: "#21140C",
    panelColor: "#180E08",
    inputColor: "#120A05",
    borderColor: "#FB923C",
    textColor: "#FFF7ED",
    mutedTextColor: "#FED7AA",
    navActiveColor: "#EA580C",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 6. VERMELHO / RUBI (RED) =================
  {
    id: "red-vivid",
    label: "Vermelho Carmesim Vívido",
    description: "Vermelho rubi intenso e dinâmico com realce luminoso de alto impacto.",
    category: "red",
    categoryLabel: "Vermelho / Rubi",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#DC2626",
    primaryColor: "#DC2626",
    secondaryColor: "#F87171",
    backgroundColor: "#160507",
    mainColor: "#22090C",
    sidebarColor: "#100305",
    rightPanelColor: "#180608",
    cardColor: "#2F0E12",
    panelColor: "#22090C",
    inputColor: "#160507",
    borderColor: "#FCA5A5",
    textColor: "#FFF1F2",
    mutedTextColor: "#FECDD3",
    navActiveColor: "#DC2626",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "red-matte",
    label: "Vinho Merlot Matte",
    description: "Vinho aveludado profundo, sofisticado e confortável para leitura e jogos.",
    category: "red",
    categoryLabel: "Vermelho / Rubi",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#991B1B",
    primaryColor: "#7F1D1D",
    secondaryColor: "#F87171",
    backgroundColor: "#15080A",
    mainColor: "#1C0C0E",
    sidebarColor: "#0F0507",
    rightPanelColor: "#15080A",
    cardColor: "#271215",
    panelColor: "#1C0C0E",
    inputColor: "#15080A",
    borderColor: "#450A0A",
    textColor: "#FFE4E6",
    mutedTextColor: "#FDA4AF",
    navActiveColor: "#7F1D1D",
    buttonTextColor: "#FFE4E6",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "red-clean",
    label: "Rubi Cristal Clean",
    description: "Design minimalista com linhas finas e detalhes em rubi refinado e translúcido.",
    category: "red",
    categoryLabel: "Vermelho / Rubi",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#E11D48",
    primaryColor: "#BE123C",
    secondaryColor: "#FECDD3",
    backgroundColor: "#120508",
    mainColor: "#18080C",
    sidebarColor: "#0E0306",
    rightPanelColor: "#130609",
    cardColor: "#220D12",
    panelColor: "#18080C",
    inputColor: "#120508",
    borderColor: "#FB7185",
    textColor: "#FFF1F2",
    mutedTextColor: "#FDA4AF",
    navActiveColor: "#BE123C",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 7. ROSA / MAGENTA (PINK) =================
  {
    id: "pink-vivid",
    label: "Rosa Choque Vívido",
    description: "Rosa magenta elétrico cyberpunk com alta saturação e brilho marcante.",
    category: "pink",
    categoryLabel: "Rosa / Magenta",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#DB2777",
    primaryColor: "#DB2777",
    secondaryColor: "#F472B6",
    backgroundColor: "#160512",
    mainColor: "#22091D",
    sidebarColor: "#10030D",
    rightPanelColor: "#180614",
    cardColor: "#2F0E27",
    panelColor: "#22091D",
    inputColor: "#160512",
    borderColor: "#F9A8D4",
    textColor: "#FDF2F8",
    mutedTextColor: "#FBCFE8",
    navActiveColor: "#DB2777",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "pink-matte",
    label: "Rosa Pastel Matte",
    description: "Tons de pétala e pau-rosa com acabamento suave, sem brilho e super relaxante.",
    category: "pink",
    categoryLabel: "Rosa / Magenta",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#9D174D",
    primaryColor: "#831843",
    secondaryColor: "#F472B6",
    backgroundColor: "#150912",
    mainColor: "#1B0E18",
    sidebarColor: "#0F060D",
    rightPanelColor: "#150912",
    cardColor: "#261421",
    panelColor: "#1B0E18",
    inputColor: "#150912",
    borderColor: "#500724",
    textColor: "#FCE7F3",
    mutedTextColor: "#F472B6",
    navActiveColor: "#831843",
    buttonTextColor: "#FCE7F3",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "pink-clean",
    label: "Quartzo Rosa Clean",
    description: "Transparência límpida com toques delicados de quartzo rosa mineral.",
    category: "pink",
    categoryLabel: "Rosa / Magenta",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#EC4899",
    primaryColor: "#BE185D",
    secondaryColor: "#FCE7F3",
    backgroundColor: "#120610",
    mainColor: "#180916",
    sidebarColor: "#0D040C",
    rightPanelColor: "#130712",
    cardColor: "#220E1F",
    panelColor: "#180916",
    inputColor: "#120610",
    borderColor: "#F472B6",
    textColor: "#FDF2F8",
    mutedTextColor: "#FBCFE8",
    navActiveColor: "#BE185D",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 8. ROXO / VIOLETA (PURPLE) =================
  {
    id: "purple-vivid",
    label: "Roxo Ultravioleta Vívido",
    description: "Violeta cósmico vibrante com brilho neon marcante e atmosfera futurista.",
    category: "purple",
    categoryLabel: "Roxo / Violeta",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#9333EA",
    primaryColor: "#9333EA",
    secondaryColor: "#C084FC",
    backgroundColor: "#10041B",
    mainColor: "#1A072B",
    sidebarColor: "#0B0213",
    rightPanelColor: "#130521",
    cardColor: "#260B3E",
    panelColor: "#1A072B",
    inputColor: "#10041B",
    borderColor: "#D8B4FE",
    textColor: "#FAF5FF",
    mutedTextColor: "#E9D5FF",
    navActiveColor: "#9333EA",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "purple-matte",
    label: "Lavanda Noturna Matte",
    description: "Tons suaves de ameixa e lavanda escura, sem cansaço visual em sessões noturnas.",
    category: "purple",
    categoryLabel: "Roxo / Violeta",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#6B21A8",
    primaryColor: "#581C87",
    secondaryColor: "#A855F7",
    backgroundColor: "#120919",
    mainColor: "#180E21",
    sidebarColor: "#0D0612",
    rightPanelColor: "#120919",
    cardColor: "#231530",
    panelColor: "#180E21",
    inputColor: "#120919",
    borderColor: "#3B0764",
    textColor: "#F3E8FF",
    mutedTextColor: "#C084FC",
    navActiveColor: "#581C87",
    buttonTextColor: "#F3E8FF",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "purple-clean",
    label: "Ametista Minimal Clean",
    description: "Cristais de ametista em uma interface límpida, translúcida e moderna.",
    category: "purple",
    categoryLabel: "Roxo / Violeta",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#8B5CF6",
    primaryColor: "#7C3AED",
    secondaryColor: "#EDE9FE",
    backgroundColor: "#0E0517",
    mainColor: "#140822",
    sidebarColor: "#0A0311",
    rightPanelColor: "#10061C",
    cardColor: "#1D0D31",
    panelColor: "#140822",
    inputColor: "#0E0517",
    borderColor: "#A78BFA",
    textColor: "#FAF5FF",
    mutedTextColor: "#DDD6FE",
    navActiveColor: "#7C3AED",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 9. ÍNDIGO / SAFIRA (INDIGO) =================
  {
    id: "indigo-vivid",
    label: "Índigo Galáctico Vívido",
    description: "Azul profundo espacial com raios índigo de alta intensidade e presença.",
    category: "indigo",
    categoryLabel: "Índigo / Safira",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#4F46E5",
    primaryColor: "#4F46E5",
    secondaryColor: "#818CF8",
    backgroundColor: "#07081A",
    mainColor: "#0D0E29",
    sidebarColor: "#050613",
    rightPanelColor: "#0A0B20",
    cardColor: "#13153D",
    panelColor: "#0D0E29",
    inputColor: "#07081A",
    borderColor: "#A5B4FC",
    textColor: "#EEF2FF",
    mutedTextColor: "#C7D2FE",
    navActiveColor: "#4F46E5",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "indigo-matte",
    label: "Crepúsculo Profundo Matte",
    description: "Índigo crepuscular aveludado e sóbrio com excelente legibilidade e paz visual.",
    category: "indigo",
    categoryLabel: "Índigo / Safira",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#3730A3",
    primaryColor: "#312E81",
    secondaryColor: "#6366F1",
    backgroundColor: "#0B0C18",
    mainColor: "#101222",
    sidebarColor: "#080911",
    rightPanelColor: "#0B0C18",
    cardColor: "#171A31",
    panelColor: "#101222",
    inputColor: "#0B0C18",
    borderColor: "#1E1B4B",
    textColor: "#E0E7FF",
    mutedTextColor: "#818CF8",
    navActiveColor: "#312E81",
    buttonTextColor: "#E0E7FF",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "indigo-clean",
    label: "Safira Pura Clean",
    description: "Safira elegante com alta clareza, transparência equilibrada e bordas nítidas.",
    category: "indigo",
    categoryLabel: "Índigo / Safira",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#6366F1",
    primaryColor: "#4338CA",
    secondaryColor: "#C7D2FE",
    backgroundColor: "#070818",
    mainColor: "#0B0D23",
    sidebarColor: "#050612",
    rightPanelColor: "#090A1D",
    cardColor: "#101334",
    panelColor: "#0B0D23",
    inputColor: "#070818",
    borderColor: "#818CF8",
    textColor: "#EEF2FF",
    mutedTextColor: "#A5F3FC",
    navActiveColor: "#4338CA",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 10. LIMA / CHARTREUSE (LIME) =================
  {
    id: "lime-vivid",
    label: "Lima Elétrica Vívido",
    description: "Verde-limão vibrante e elétrico com energia gamer radiante e dinâmica.",
    category: "lime",
    categoryLabel: "Lima / Neon",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#84CC16",
    primaryColor: "#84CC16",
    secondaryColor: "#BEF264",
    backgroundColor: "#0A1504",
    mainColor: "#112306",
    sidebarColor: "#070E02",
    rightPanelColor: "#0D1A05",
    cardColor: "#1A340A",
    panelColor: "#112306",
    inputColor: "#0A1504",
    borderColor: "#D9F99D",
    textColor: "#F7FEE7",
    mutedTextColor: "#D9F99D",
    navActiveColor: "#84CC16",
    buttonTextColor: "#0A1504",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "lime-matte",
    label: "Oliva Suave Matte",
    description: "Tom de oliva e sálvia quente sem reflexos, aconchegante e natural para os olhos.",
    category: "lime",
    categoryLabel: "Lima / Neon",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#4D7C0F",
    primaryColor: "#3F6212",
    secondaryColor: "#84CC16",
    backgroundColor: "#0F1509",
    mainColor: "#151E0D",
    sidebarColor: "#0B0F06",
    rightPanelColor: "#0F1509",
    cardColor: "#1E2A13",
    panelColor: "#151E0D",
    inputColor: "#0F1509",
    borderColor: "#1A2E05",
    textColor: "#ECFCCB",
    mutedTextColor: "#A3E635",
    navActiveColor: "#3F6212",
    buttonTextColor: "#ECFCCB",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "lime-clean",
    label: "Broto Bio Clean",
    description: "Toques de lima fresco com fundo translúcido e visual orgânico minimalista.",
    category: "lime",
    categoryLabel: "Lima / Neon",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#65A30D",
    primaryColor: "#65A30D",
    secondaryColor: "#ECFCCB",
    backgroundColor: "#091204",
    mainColor: "#0E1A06",
    sidebarColor: "#060D03",
    rightPanelColor: "#0B1505",
    cardColor: "#152709",
    panelColor: "#0E1A06",
    inputColor: "#091204",
    borderColor: "#A3E635",
    textColor: "#F7FEE7",
    mutedTextColor: "#BEF264",
    navActiveColor: "#65A30D",
    buttonTextColor: "#000000",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 11. CAFÉ / ÂMBAR (BROWN) =================
  {
    id: "brown-vivid",
    label: "Âmbar Caramelo Vívido",
    description: "Caramelo dourado tostado com brilho âmbar profundo e contrastes expressivos.",
    category: "brown",
    categoryLabel: "Café / Âmbar",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#D97706",
    primaryColor: "#D97706",
    secondaryColor: "#FBBF24",
    backgroundColor: "#160E06",
    mainColor: "#23170A",
    sidebarColor: "#0F0A04",
    rightPanelColor: "#191007",
    cardColor: "#31200D",
    panelColor: "#23170A",
    inputColor: "#160E06",
    borderColor: "#FCD34D",
    textColor: "#FFFBEB",
    mutedTextColor: "#FDE68A",
    navActiveColor: "#D97706",
    buttonTextColor: "#160E06",
    backgroundOpacity: 0.95,
    mainOpacity: 0.44,
    surfaceOpacity: 0.84,
    panelOpacity: 0.74,
    inputOpacity: 0.92,
    sidebarOpacity: 0.93,
    rightPanelOpacity: 0.87,
    navActiveOpacity: 0.22,
    borderOpacity: 0.24,
    backgroundImageOpacity: 0.24,
    sidebarImageOpacity: 0.24,
  },
  {
    id: "brown-matte",
    label: "Café Expresso Matte",
    description: "Café escuro torrado e chocolate aveludado, macio e extremamente aconchegante.",
    category: "brown",
    categoryLabel: "Café / Âmbar",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#78350F",
    primaryColor: "#592608",
    secondaryColor: "#B45309",
    backgroundColor: "#15100C",
    mainColor: "#1C1510",
    sidebarColor: "#0F0B08",
    rightPanelColor: "#15100C",
    cardColor: "#271E17",
    panelColor: "#1C1510",
    inputColor: "#15100C",
    borderColor: "#451A03",
    textColor: "#FEF3C7",
    mutedTextColor: "#D97706",
    navActiveColor: "#592608",
    buttonTextColor: "#FEF3C7",
    backgroundOpacity: 0.92,
    mainOpacity: 0.36,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.14,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "brown-clean",
    label: "Moca Latte Clean",
    description: "Visual cremoso translúcido inspirado em café latte e madeira nobre suave.",
    category: "brown",
    categoryLabel: "Café / Âmbar",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#B45309",
    primaryColor: "#92400E",
    secondaryColor: "#FEF3C7",
    backgroundColor: "#120D08",
    mainColor: "#18120C",
    sidebarColor: "#0D0906",
    rightPanelColor: "#130E09",
    cardColor: "#221910",
    panelColor: "#18120C",
    inputColor: "#120D08",
    borderColor: "#D97706",
    textColor: "#FFFBEB",
    mutedTextColor: "#FDE68A",
    navActiveColor: "#92400E",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },

  // ================= 12. MONOCROMÁTICO (MONO) =================
  {
    id: "mono-vivid",
    label: "Obsidiana Neon Vívido",
    description: "Preto absoluto com bordas brancas elétricas e contraste cirúrgico de alta precisão.",
    category: "mono",
    categoryLabel: "Monocromático",
    style: "vivid",
    styleLabel: "Vívido",
    swatchColor: "#FFFFFF",
    primaryColor: "#FFFFFF",
    secondaryColor: "#E2E8F0",
    backgroundColor: "#030304",
    mainColor: "#08080B",
    sidebarColor: "#020203",
    rightPanelColor: "#050507",
    cardColor: "#0F0F14",
    panelColor: "#08080B",
    inputColor: "#030304",
    borderColor: "#FFFFFF",
    textColor: "#FFFFFF",
    mutedTextColor: "#CBD5E1",
    navActiveColor: "#FFFFFF",
    buttonTextColor: "#000000",
    backgroundOpacity: 0.98,
    mainOpacity: 0.5,
    surfaceOpacity: 0.9,
    panelOpacity: 0.8,
    inputOpacity: 0.95,
    sidebarOpacity: 0.96,
    rightPanelOpacity: 0.9,
    navActiveOpacity: 0.25,
    borderOpacity: 0.3,
    backgroundImageOpacity: 0.2,
    sidebarImageOpacity: 0.2,
  },
  {
    id: "mono-matte",
    label: "Carbono Furtivo Matte",
    description: "Cinza grafite e carbono fosco, sem reflexos e com descanso visual total para sessões longas.",
    category: "mono",
    categoryLabel: "Monocromático",
    style: "matte",
    styleLabel: "Matte",
    swatchColor: "#64748B",
    primaryColor: "#475569",
    secondaryColor: "#94A3B8",
    backgroundColor: "#0D0F12",
    mainColor: "#13161A",
    sidebarColor: "#0A0C0E",
    rightPanelColor: "#0D0F12",
    cardColor: "#1A1E24",
    panelColor: "#13161A",
    inputColor: "#0D0F12",
    borderColor: "#2A303C",
    textColor: "#F1F5F9",
    mutedTextColor: "#94A3B8",
    navActiveColor: "#475569",
    buttonTextColor: "#F1F5F9",
    backgroundOpacity: 0.92,
    mainOpacity: 0.35,
    surfaceOpacity: 0.76,
    panelOpacity: 0.68,
    inputOpacity: 0.88,
    sidebarOpacity: 0.91,
    rightPanelOpacity: 0.84,
    navActiveOpacity: 0.16,
    borderOpacity: 0.12,
    backgroundImageOpacity: 0.18,
    sidebarImageOpacity: 0.18,
  },
  {
    id: "mono-clean",
    label: "Vidro Puro Clean",
    description: "Visual clean com estética moderna de vidro fosco translúcido e máxima clareza.",
    category: "mono",
    categoryLabel: "Monocromático",
    style: "clean",
    styleLabel: "Clean",
    swatchColor: "#38BDF8",
    primaryColor: "#0284C7",
    secondaryColor: "#E2E8F0",
    backgroundColor: "#080C14",
    mainColor: "#0E1420",
    sidebarColor: "#060910",
    rightPanelColor: "#090E18",
    cardColor: "#121A2A",
    panelColor: "#0E1420",
    inputColor: "#080C14",
    borderColor: "#38BDF8",
    textColor: "#F8FAFC",
    mutedTextColor: "#CBD5E1",
    navActiveColor: "#0284C7",
    buttonTextColor: "#FFFFFF",
    backgroundOpacity: 0.88,
    mainOpacity: 0.32,
    surfaceOpacity: 0.66,
    panelOpacity: 0.56,
    inputOpacity: 0.86,
    sidebarOpacity: 0.87,
    rightPanelOpacity: 0.81,
    navActiveOpacity: 0.18,
    borderOpacity: 0.16,
    backgroundImageOpacity: 0.22,
    sidebarImageOpacity: 0.22,
  },
];

export const findPresetById = (id?: string): AppearancePreset | undefined =>
  appearancePresets.find((preset) => preset.id === id);
